### PR TITLE
Directors' Portal styling + card templates

### PR DESCRIPTION
**Pull request by DerangedMind**
Added styling for login page, navigation bar, and counselor index page (in director portal). 

Also added redirect for directors and parents on login. Directors go to dashboard and parents go to their parent show page.

### CODE REVIEW

**Comment by DerangedMind** [comment]
Added kids & counselors to dashboard. That means I've created some templates that can be used to load "cards". 

Specificlly, look @ 
[counsellors.scss](https://github.com/DerangedMind/fluffy-camp-fire/pull/23/files#diff-738ac3959775eb74ae88726a9130a2af) for CSS
[dshbord index pge](https://github.com/DerangedMind/fluffy-camp-fire/pull/23/files#diff-73714757b537df64b7e56a41357fbccf) for HTML & Templtes

### How it works

This is the bsic structure of crds, but you will hve to ply round with it for individul use cses. 😁 

```html
<div class="item-list">
  <% @counselors.each do |counselor| %> 
    <div class="row user-card">
      <div class="col-xs-2">X</div>
      <div class="col-xs-5">Y</div>
      <div class="col-xs-5">Z</div>
    </div>
  <% end %>
</div>
```

**Comment by DerangedMind** [comment]
screen shot 2017-08-16 at 3 59 18 am
screen shot 2017-08-16 at 3 59 34 am
screen shot 2017-08-16 at 3 59 02 am
screen shot 2017-08-15 at 5 21 51 pm
screen shot 2017-08-15 at 5 21 42 pm

**Comment by Garo-A** [comment]
THE SIDE NAV YEAHHHHHHHHHHH 
You have to show me how you did that.

**Comment by TheTempas** [comment]
GORGEOUS

**Pull request merged**
